apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"ms-auth"},"name":"meta-ms-auth","namespace":"meta-ms"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"meta-ms-auth"}},"template":{"metadata":{"labels":{"app":"meta-ms-auth"}},"spec":{"containers":[{"image":"jmartinezblanco/meta-ms-auth","name":"meta-ms-auth","ports":[{"containerPort":3000}]}]}}}}
  creationTimestamp: "2024-04-25T18:40:16Z"
  generation: 7
  labels:
    app.kubernetes.io/instance: ms-auth
  name: meta-ms-auth
  namespace: meta-ms
  resourceVersion: "6261022"
  uid: ec4f37c7-1ed8-413c-9a6b-1df7278502e7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: meta-ms-auth
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: meta-ms-auth
    spec:
      containers:
      - env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: DB_USERNAME
              name: db-secret
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: db-secret
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: DB_NAME
              name: db-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: db-secret
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: DB_PORT
              name: db-secret
        - name: JWT_SECRET
          value: m3t4s3cr37
        - name: JWT_EXP_IN
          value: 8h
        - name: JWT_CODE_VALIDATION_EXP_IN
          value: 2h
        - name: MAIL_DRIVER
          value: smtp
        - name: MAIL_HOST
          value: transfer.digbang.com
        - name: MAIL_POST
          value: "465"
        - name: MAIL_USERNAME
          value: delivery@transfer.digbang.com
        - name: MAIL_PASSWORD
          value: who2l.mHGCIn
        - name: MAIL_ENCRYPTION
          value: ssl
        - name: MAIL_FROM_ADDRESS
          value: meta@digbang.com
        - name: MAIL_FROM_NAME
          value: Meta
        - name: META_PROJECT_URL
          value: https://ms-projects.fusion.com.ar
        - name: META_SPA_URI
          value: https://meta-spa.fusion.com.ar
        - name: OAUTH_CLIENT_ID
          value: m3T4f0rm3R5-qa
        - name: OAUTH_CLIENT_SECRET
          value: SB)q2VQXTd$4ZZnS-qa
        image: iad.ocir.io/idwwmbyiyhww/meta-ms-auth:latest
        imagePullPolicy: Always
        name: meta-ms-auth
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: volume-pvsgj
        secret:
          defaultMode: 420
          secretName: fusion-cert
