apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-04-25T23:27:15Z"
  labels:
    app.kubernetes.io/instance: ms-auth
  name: meta-ms-auth
  namespace: meta-ms
  resourceVersion: "5388308"
  uid: 2a3657b2-29e2-4a12-9b8d-ce58c0701f82
spec:
  clusterIP: 172.30.150.32
  clusterIPs:
  - 172.30.150.32
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: meta-ms-auth
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
